fix: When using search-config-v2 make the order of engines behave the same as desktop (bug 1895740)
mozilla-extensions/searchengine-devtools pull request #168
Opened 2024-05-08 16:05 UTC by Standard8

This adds search order handling to be the same as desktop. It is possible that we could move desktop's sort function to a function that we could call from the extension as well - but we would still need a fallback (at least in the short term) for the current versions of FF, and overall, I'm not sure if it is worth it as it isn't something we generally update.

2024-05-16 03:02 UTC, mandysGit commented on extension/content/enginesView.mjs
> +      }
I suggest adding the same comment as the Desktop code: 
> The app default engine should always be first in the list (except
    for distros, that we should respect).

2024-05-16 03:04 UTC, mandysGit commented on extension/content/enginesView.mjs
> +      }
This doesn't look equivalent to the desktop version. 
How are we checking that `privateDefault` is not the same as the `defaultEngine` here? 

You might want to add same comment too: 
>   if there's a private default, and it is different to the normal
     default, then it should be second in the list.

2024-05-16 03:06 UTC, mandysGit reviewed
I added comments for review.

2024-05-16 03:07 UTC, mandysGit requested changes
I added comments for review.

2024-05-16 03:08 UTC, mandysGit commented on extension/content/enginesView.mjs
> +      if (a._orderHint && b._orderHint) {
Might as well add this comment too? 
> We sort by highest orderHint first, then alphabetically by name.

2024-05-21 23:55 UTC, mandysGit commented
Hi @Standard8 , 
Sorry I forgot to write an update here after our meeting last week. 

IIRC, you're investigating on how to make `_sortEnginesByDefaults` public so we can call it from search engine dev tools; rather than re-writing an equivalent sort function in this repo. 

Should we close out this PR then?

2024-05-22 14:19 UTC, Standard8 commented
I'll update the desktop code & this PR together.

2024-06-12 16:32 UTC, Standard8 commented
@mandysGit I've updated this PR and also attached a patch to [bug 1895740](https://bugzilla.mozilla.org/show_bug.cgi?id=1895740) for the required mozilla-central changes.

2024-06-14 19:31 UTC, mandysGit approved these changes
Looks good. Just added 1 comment for variable name change suggestion. 

I already approved https://phabricator.services.mozilla.com/D213440

2024-06-14 19:31 UTC, mandysGit commented on extension/experiments/searchengines/api.js
> +  if (usingV2 && "sortEnginesByDefaults" in SearchUtils) {
Could we change `usingV2` to `useSearchConfigV2` ?

2024-06-17 09:03 UTC, merged