Add table to display engine search, suggest, and trending URLs.
mozilla-extensions/searchengine-devtools pull request #185
Opened 2024-06-28 05:27 UTC by mandysGit

2024-07-03 13:01 UTC, Standard8 requested changes
Thank you, this is looking good and definitely will be nice to have. I've commented in-line for a few places where I think we can improve it further.

2024-07-20 00:31 UTC, mandysGit commented on extension/content/engineUrlView.mjs
> +      "Results",
👍 

I'll create a follow up bug for this.

2024-07-20 00:57 UTC, mandysGit commented on extension/content/engineUrlView.mjs
> +      "Results",
[Bug 1909017 - Update search engine dev tools to show results from suggest or trending urls](https://bugzilla.mozilla.org/show_bug.cgi?id=1909017)

2024-07-22 20:06 UTC, mandysGit commented on extension/content/engineUrlView.mjs
> +    let tbody = this.createTableBody(rowHeaders);
I used `createThead`, `createTBody`, `insertRow` methods where I could.

For some of the elements, I still needed to use `document.createElement`.

2024-07-22 23:06 UTC, mandysGit commented
Addressed in-line review comments. This is ready for another review.

2024-07-24 08:16 UTC, Standard8 reviewed
I added the extra tweaks I suggested to clear the table when other items are suggested. We should probably fix the flickering at some stage, but this is a good improvement to get landed.

2024-07-24 08:16 UTC, Standard8 approved these changes

2024-07-24 08:17 UTC, merged