Suggestions view
mozilla-extensions/searchengine-devtools pull request #213
Opened 2024-11-15 13:48 UTC by moritzbeier

This adds another table where the search and trending suggestions are previewed.

2024-11-15 13:52 UTC, moritzbeier commented on extension/content/loader.mjs
> +  "https://raw.githubusercontent.com/mozilla/gecko-dev/refs/heads/master/browser/locales/all-locales";
This significantly improved the loading time for me (fetching the `hg.mozilla.org` url takes up to 17 _seconds_) but I'm not sure it's a good idea.

2024-11-18 17:10 UTC, Standard8 requested changes
Thank you for working on this. As mentioned in-line, I think we should change improving the startup to a separate patch - there's a few things we could do there.

The rest of the patch looks good, and generally works well. There's one part that I find a bit misleading - in some cases (wikipedia, eBay) they don't have suggestions for "Cute Kitten".

I think either we need to change that to something more general (but then we might also struggle with some of the language specific engines), or maybe it is enough to show that "0 results were found" assuming there were no actual errors in communicating with the server. Another option might be allowing to change the search term, though I'm not sure that's totally necessary.

I'm open to ideas here - the main aim is to clarify if the suggestions are working or not, but displaying the results can be useful as well.

2024-11-20 11:03 UTC, moritzbeier commented on extension/content/loader.mjs
> +  "https://raw.githubusercontent.com/mozilla/gecko-dev/refs/heads/master/browser/locales/all-locales";
We could definitely cache the locales but to you see an issue with pinging Github in particular? I thought mozilla-central will move to Github soon anyway and their infrastructure is just so much faster than ours.

2024-11-21 20:29 UTC, Standard8 approved these changes
Thank you, this looks good. The way the results are handled are much better.

One thought I did have - what do you think about auto-scrolling to the top of the page when the results are received? I think it might be easier/make it clearer that they're there.

2024-11-21 20:32 UTC, Standard8 commented
Additional thought, please could you also bump the version number in `package.json` and in `extension/manifest.json` to `2.6.0`?

That'll make it easier for us to do the release.

2024-11-22 10:37 UTC, moritzbeier commented
This should make it clear

2024-11-22 12:34 UTC, merged